# Generated by Django 5.0.4 on 2024-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Питання',
            },
        ),
        migrations.AddField(
            model_name='calculator',
            name='concrete_type',
            field=models.CharField(choices=[('C8/10', 'C8/10 (3500 UAH/m³)'), ('C15/20', 'C15/20 (3800 UAH/m³)'), ('C25/30', 'C25/30 (4000 UAH/m³)')], default='C8/10', max_length=50),
        ),
    ]
