# Generated by Django 5.0.4 on 2024-04-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0002_question_calculator_concrete_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
