# Generated by Django 5.0.4 on 2024-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0006_category_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
